/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JOptionPane;
import controller.*;
import javax.swing.JFrame;
import model.*;

public class AddAccountMenu extends javax.swing.JDialog {
    
private BankAccount bankAcc=null;
private Bank bank;
private BusinessLogic bisLogic;

    public BankAccount getBankAcc() {
        return bankAcc;
    }

    public void setBankAcc(BankAccount bankAcc) {
        this.bankAcc = bankAcc;
    }

    public AddAccountMenu(java.awt.Frame parent, boolean modal, BusinessLogic bisLogic) {
     super(parent, modal);
        initComponents();
        setSize(250,250);
        setLocationRelativeTo(parent);   
        this.bisLogic = bisLogic;    
        this.bankAcc= null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        FirstNameLabel = new javax.swing.JLabel();
        FirstNameField = new javax.swing.JTextField();
        LastNameLabel = new javax.swing.JLabel();
        LastNameField = new javax.swing.JTextField();
        DepositLabel = new javax.swing.JLabel();
        DepositField = new javax.swing.JTextField();
        TypeLabel = new javax.swing.JLabel();
        TypeField = new javax.swing.JComboBox();
        OKButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jTextField1.setText("jTextField1");

        jLabel2.setText("jLabel2");

        jLabel3.setText("jLabel3");

        jLabel10.setText("jLabel10");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Account Menu");
        getContentPane().setLayout(new java.awt.GridLayout(5, 2, 5, 10));

        FirstNameLabel.setText("FirstName");
        getContentPane().add(FirstNameLabel);

        FirstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameFieldActionPerformed(evt);
            }
        });
        getContentPane().add(FirstNameField);

        LastNameLabel.setText("LastName");
        getContentPane().add(LastNameLabel);
        getContentPane().add(LastNameField);

        DepositLabel.setText("Initial Deposit");
        getContentPane().add(DepositLabel);
        getContentPane().add(DepositField);

        TypeLabel.setText("Account Type");
        getContentPane().add(TypeLabel);

        TypeField.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Checking", "Saving" }));
        TypeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TypeFieldActionPerformed(evt);
            }
        });
        getContentPane().add(TypeField);

        OKButton.setBackground(new java.awt.Color(200, 200, 200));
        OKButton.setText("OK");
        OKButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OKButtonActionPerformed(evt);
            }
        });
        getContentPane().add(OKButton);

        CancelButton.setText("Cancel");
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CancelButton);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TypeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TypeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TypeFieldActionPerformed

    private void FirstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstNameFieldActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void OKButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OKButtonActionPerformed
        // Verify FIelds
       String name;
       String lastname;
       Double deposit = null;
       BankAccount account=null;
        if(FirstNameField.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "FirstName must not be empty", "Input error", JOptionPane.WARNING_MESSAGE);
            return;
        }else {
            name = FirstNameField.getText();
        }
        
        if(LastNameField.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "LastName must not be empty", "Input error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        else {
            lastname = LastNameField.getText();
        }
        
         if(DepositField.getText().isEmpty()){
            JOptionPane.showMessageDialog(this, "Initial deposit must be entered", "Input error", JOptionPane.WARNING_MESSAGE);
            return;
        }
        else {
             try{
                 deposit = Double.parseDouble(DepositField.getText());
             }
             catch (NumberFormatException ex){
                 JOptionPane.showMessageDialog(this, "Initial deposit must be a nubmer", "Input error", JOptionPane.WARNING_MESSAGE);
             }
             
             JOptionPane.showMessageDialog(this, name+ "\n"+lastname+"\n"+deposit);
             
             Owner owner = new Owner();
             owner.setFirstName(name);
             owner.setLastName(lastname);
             String type = TypeField.getSelectedItem().toString();
             
        if (type == "Checking"){
            bankAcc = new BankAccount();
        }
        else{
            bankAcc = new SavingAccount();
            System.out.println("Epta! Save");
            bankAcc.setInterest(deposit);
            JOptionPane.showConfirmDialog(this, "Deposit $" + String.format("%.2f", deposit)
                        + " to the account?\nInterest Earned: $" +
                        String.format("%.2f", (bankAcc.getInterest() * deposit)));
        }                
        
            bankAcc.setOwner(owner);
            bankAcc.setBalance(deposit);
            this.bisLogic.newAccount(bankAcc);
            this.dispose();
            JOptionPane.showMessageDialog(this, "Your account is successfully created with initial deposit :\n"
                    +bankAcc.getBalance());             
        }
    }//GEN-LAST:event_OKButtonActionPerformed

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JTextField DepositField;
    private javax.swing.JLabel DepositLabel;
    private javax.swing.JTextField FirstNameField;
    private javax.swing.JLabel FirstNameLabel;
    private javax.swing.JTextField LastNameField;
    private javax.swing.JLabel LastNameLabel;
    private javax.swing.JButton OKButton;
    private javax.swing.JComboBox TypeField;
    private javax.swing.JLabel TypeLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
